```{r}
library(knitr)
```

---
title: "SaniPath Exposure Assessment Report"
author: "Yuke Wang"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document: null
  pdf_document: default
  toc: yes
---

This is a test version of **SaniPath** tool report. This report can be download as 'HTML', 'PDF', and 'MS word' documents.
For any infomration and questions, please contact [Yuke Wang](yuke.wang@emory.edu).

# Results:

```{r, echo=FALSE, results='asis'}
for (n in 1:length(report())) {
  cat("##", names(report()[n]),"\n")
  for (a in 1:length(report()[[n]])) {
    cat("###", names(report()[[n]][a]), "\n")
    sub <- report()[[n]][[a]]
    
    verb <- 'are'
    if (length(sub$dominant) > 2) {
        dominant <- paste(sub$dominant[1:(length(sub$dominant) - 1)], collapse=", ")
        dominant <- paste0(dominant, ', and ', sub$dominant[length(sub$dominant)])
    }
    else if (length(sub$dominant) == 2) {
      dominant <- paste(sub$dominant, collapse=' and ')
    }
    else {
      dominant <- sub$dominant
      verb <- 'is'
    }
    cat("The dominant pathways identified", verb, dominant, "\n")
    # print(as.data.frame(sub$matrix))
  }
}
```

```{r}
print(matrix(NA, nrow=2, ncol=2))
```

